<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

In [1]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [3]:
import numpy as np
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [4]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.2 Accessing data from a list (or array)

In [5]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [6]:
py_super_names[0]

'Black Widow'

## 1.3 Accessing data from a dictionary

In [7]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

In [8]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

## 1.4 Higher dimensional lists

In [9]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

# 2 Lists vs. Arrays

## 2.1 Size

In [10]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array

In [11]:
len(py_list_2d)
len(np_array_2d)
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [12]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)
py_list
np_array

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [15]:
py_list = [1, 1.5, 2]
np_array = np.array(py_list)
np_array + 10
#py_list + 10        # Won't work!

array([11. , 11.5, 12. ])

## 2.4 Adding another list

In [16]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)
py_list_1 + py_list_2
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [19]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
py_list*2
print(py_list*2)
np_array*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

In [20]:
np_array**2
#py_list**2                      # Won't work!  

array([ 1,  4,  9, 16, 25])

## 2.7 Asking questions

In [21]:
py_list == 3     # Works, but what IS the question?
np_array == 3  
np_array > 3  

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [22]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

1.4142135623730951

# Exercises & Self-Assessment

In [23]:

import numpy as np
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    # Prints 'a1'
                    # Prints 'c3'
                    # Prints 'e5'
                    # Prints 'g7'
print(py_list[0], py_list[2], py_list[4], py_list[6], py_list[8])   # Prints 'i9'

elements = ['Hydrogen',
            'Helium', 'Lithium',
            'Beryllium', 'Boron', 'Carbon',
            'Nitrogen', 'Oxygen',
            'Fluorine',
            'Neon']
print(elements[4], elements[-6])

numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  
print(numbers.count(1))
count_1 = np.array(numbers)
count_1_output = (count_1 == 1).sum()
print(count_1_output)    
# Your solution here




a1 c3 e5 g7 i9
Boron Boron
9
9


## Footnotes

In [ ]:
import random

# List of words for the game
words_list = ["python", "programming", "challenge", "coding", "algorithm"]

# Select a random word from the list
secret_word = random.choice(words_list)

# Number of attempts allowed
attempts = 5

# Dictionary to store user scores
user_scores = {}

def wordle_game():
    # Initialize user's score to 0
    user_score = 0

    print("Welcome to the Wordle Game!")
    print("Try to guess the secret word within 5 attempts.")

    # List to store correct guesses
    correct_guesses = ['_' for _ in range(len(secret_word))]

    while attempts > 0:
        print("Current Progress:", " ".join(correct_guesses))
        
        user_guess = input("Enter your guess: ").lower()

        if user_guess == secret_word:
            print("Congratulations! You guessed the correct word:", secret_word)
            user_score += 1
            break

        for i in range(len(secret_word)):
            if user_guess[i] == secret_word[i]:
                correct_guesses[i] = user_guess[i]

        print("Incorrect guess. Keep trying!")
        attempts -= 1

    if attempts == 0:
        print("Out of attempts! The secret word was:", secret_word)

    return user_score

# Play the game with three users
for i in range(3):
    user_name = input("Enter your name: ")
    score = wordle_game()
    user_scores[user_name] = score

print("Game Over! User Scores:")
for user, score in user_scores.items():
    print(f"{user}: {score} points")