<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [2]:
import numpy as np
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
my_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

## 1.2 Arrays only | Subsetting by masking

In [3]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [4]:
np_array[~(np_array > 3)]                 # '~' means 'NOT'

array([1, 2, 3])

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [6]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)
py_list_2d[:3][0]
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

## 1.4 Growing lists

In [7]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [8]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x
x=[1]
x+= [2]
x+= [3]
x+= [4]
x
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [9]:
x = [1, 2, 3]
x += [4, 5, 6]
x
x=[1, 2, 3]
x.extend([4, 5, 6])
x
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [10]:
a=(1, 2, 3)     # Define tuple cannot change

## 1.6 Be VERY careful when copying

In [11]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

# Exercises & Self-Assessment

In [13]:

import numpy as np

# Given 2D NumPy array
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"], [5, "E"], [7, "G"], [6, "F"], [8, "H"], [10, "J"], [9, "I"]])

# Create a boolean mask for odd numbers using np.where
mask = np.where((np_array_2d[:, 0].astype(int) % 2 != 0), True, False)

# Use the mask to subset the letters corresponding to the odd numbers
# result = list(
    
np_array_2d[mask, 1]

# print(result)

# Your solution here




array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')

## Footnotes